paste.define("health.base",["paste.dom","paste.util","paste.event","paste.has"],function(d,c,h,e,i){var j=[],k=i.touch,d=c.get("jawbone-nav"),f=window.location.hash,l=c.Bounds.fromElement(d).height-10,g=function(a){var b=new e.Event(window,"smoothscroll");b.fire({newURL:a,verticalOffset:k?10:l+10});b.dispose()};(function(){f&&(window.scrollTo(0,0),g(f.slice(1)));h.each(c.querySelectorAll(".smoothscroll-break"),function(a){j.push(new e.Event.Subscription("click",a,function(b){b.preventDefault();g(a.hash.slice(1))}))})})()});
paste.define("jawbone.ui.carousel",["paste.dom","paste.util","paste.event","paste.guid"],function(q,c,l,f,y){var r={},s,m,p=function(a,b,t){var g=this,u,w=c.get(".jawbone-carousel-items",a)[0],e=c.get(".jawbone-carousel-item",a),h=e.length,j,k,q="ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch,x=function(){if(a){var d=a.getAttribute("data-jawbone-carousel-controlsparent");if(d=c.get(d))return d}return a}(),r=a&&a.hasAttribute("data-jawbone-carousel-indicate"),s=a&&
a.hasAttribute("data-jawbone-carousel-autocycle"),m=a&&a.hasAttribute("data-jawbone-carousel-count"),p=a&&a.hasAttribute("data-jawbone-carousel-broadcast-moves"),b=b||!1,z=null,n=null,i=null,v=null,o,A=function(d,a){null!==n&&(c.removeCssClass(n,"jawbone-carousel-controls-inactive"),n=null);d===h-1?(c.addCssClass(j,"jawbone-carousel-controls-inactive"),n=j):0===d&&(c.addCssClass(k,"jawbone-carousel-controls-inactive"),n=k);null!==v&&(v.classList.remove("jawbone-carousel-indicator-item-active"),v=
null);i&&(i.childNodes[d].classList.add("jawbone-carousel-indicator-item-active"),v=i.childNodes[d]);s&&(window.clearInterval(z),z=window.setInterval(function(a){return function(){d=g.current+1;if(d===h){a.goTo(0);d=0}else a.goTo(d)}}(a),5E3))};this.el=a;this.guid=t||y.Guid.create();this.events=[];this.resizeSub=new f.Event.Subscription("resize",window,function(){this.goTo(g.current,!0,!0)},this);this.current=0;this.type="carousel";this.total=h;this.slides=e;this.carouselName=b;this.goTo=function(a,
b,e){a>h-1?a=h-1:0>a&&(a=0);if(!b&&a===g.current)return!1;e&&c.addCssClass(w,"carousel-no-transition");var f=c.Bounds.fromElement(this.el);w.style.left=-(f.width*a)+"px";A(a,this);g.current=a;m&&(o.textContent=(g.current+1).toString());p&&!b&&this.broadcastEvent.fire(this);e&&window.setTimeout(function(){c.removeCssClass(w,"carousel-no-transition")},0)};(function(){u=document.createDocumentFragment();var a=document.createElement("ul");j=document.createElement("li");k=document.createElement("li");
a.className="jawbone-carousel-controls";j.className="jawbone-carousel-controls-next";k.className="jawbone-carousel-controls-prev";a.appendChild(k);a.appendChild(j);u.appendChild(a);x.appendChild(a)})();(function(){if(r){c.addCssClass(a,"jawbone-carousel-indicators");var d=document.createElement("ul"),b,e;c.addCssClass(d,"jawbone-carousel-indicator");for(b=0;b<h;b+=1)e=document.createElement("li"),c.addCssClass(e,"jawbone-carousel-indicator-item"),d.appendChild(e);u.appendChild(d);i=d;a.appendChild(u)}})();
m&&(t=document.createDocumentFragment(),c.addCssClass(a,void 0),e=document.createElement("div"),c.addCssClass(e,"jawbone-carousel-counter"),o=document.createElement("span"),c.addCssClass(o,"counter-current"),o.textContent=(g.current+1).toString(),e.appendChild(o),b=document.createElement("span"),c.addCssClass(b,"counter-divider"),b.textContent="/",e.appendChild(b),b=document.createElement("span"),c.addCssClass(b,"counter-total"),b.textContent=h,e.appendChild(b),t.appendChild(e),a.appendChild(t));
q&&(c.addCssClass(a,"jawbone-carousel-touch"),x!==a&&c.addCssClass(x,"jawbone-carousel-touch"));this.events.push(new f.Event.Subscription("click",j,function(){this.goTo(g.current+1)},this));this.events.push(new f.Event.Subscription("click",k,function(){this.goTo(g.current-1)},this));p&&(this.broadcastEvent=new f.Event(window,"carouselMove"));i&&l.each(i.childNodes,function(a,b){this.events.push(new f.Event.Subscription("click",i.childNodes[b],function(){this.goTo(b)},this))},this);A(0,this);c.addCssClass(a,
"jawbone-carousel-loaded")};p.prototype={dispose:function(){l.each(this.events,function(a){a.remove()});delete this.el;delete this.guid;delete this.events;this.resizeSub.remove();this.resizeSub=null;delete this.resizeSub},register:function(a){l.mixin(this,a)}};s=c.get(".jawbone-carousel",!0);f.DocumentEvent.loaded(function(){l.each(s,function(a){var b=a&&a.hasAttribute("data-jawbone-carousel-name")?a.getAttribute("data-jawbone-carousel-name"):!1,c=y.Guid.create();r[b||c]=new p(a,b,c)});q=l.mixin(q,
r);m=new f.Event(window,"carouselsBuilt");m.fire()})});
paste.define("jawbone.ui.colorizer",["paste.dom","paste.util","paste.event"],function(d,a,g,j){var d=a.get(".jawbone-colorizer",!0),h=[],p=[],q=function(b){var d=a.get(".jawbone-colorizer-swatches",b)[0],e=a.get(".jawbone-colorizer-active",b)[0],k=a.get(".jawbone-colorizer-label",b)[0],f=a.get(".shop-button",b)[0],g=f?f.href:!1,l=b.getAttribute("data-default")||"onyx",c,m,n,h=e.nodeName.toLowerCase(),o=function(i){a.removeCssClass(e,"jawbone-colorizer-active");a.removeCssClass(b,n);a.addCssClass(b,
i);a.addCssClass(c,"jawbone-colorizer-active");k&&(k.textContent=c.textContent);n=i;e=c;f&&(f.href=g+"#medium_"+i)};p.push(new j.Event.Subscription("click",d,function(a){c=j.Event.getEventTarget(a);c===e||c.nodeName.toLowerCase()!==h||(m=c.getAttribute("data-jawbone-colorizer-color"),o(m))}));c=a.get("."+l,b)[0];o(l)};g.each(d,function(a){h.push(new q(a))})});
paste.define("jawbone.ui.smoothscroll",["paste.util","paste.dom","paste.event"],function(B,p,e,f){var x="ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch,a,j=Math.round,k=Math.min,y=Math.max,z=Math.abs,l=new f.Event.Subscription("mousewheel",window,function(){window.clearTimeout(a);a=null}),b,g,h,m,q=0,c,n,r,o,i,s,t,u=new f.Event(window,"smoothscroll"),v=u.subscribe(function(b,d){var a=!0;g=e.get(d?"#"+d.newURL:window.location.hash,!0)[0];c=e.Bounds.fromElement(g).top;
d&&d.verticalOffset&&(q=d.verticalOffset,c-=q);g&&(d&&d.hasOwnProperty("updateHash")&&(a=p.parseBoolean(d.updateHash)),l.attach(),s=g.id,t=a,n())}),w,A=[];n=function(){b=e.getScrollTop();x?window.scrollTo(0,c):c>b?(h=j((e.getScrollHeight()-(b+e.getViewportHeight()))/3),h=k(j((c-b)/3),h),m=y(2,k(h,400))):m=-k(z(j((c-b)/3)),400);i?i.attach():i=o.subscribe(r);window.scrollTo(0,b+m);window.setTimeout(function(){o.fire()},50)};r=function(){i.detach();1>=Math.abs(b-c)||e.getScrollTop()===b?(window.scrollTo(0,
c),window.clearTimeout(a),a=null,v.detach(),t&&(window.history&&history.pushState)&&history.pushState({},document.title,"#"+s),v.attach(),l.detach()):(window.clearTimeout(a),a=setTimeout(n,50))};w=function(a){"A"===a.target.nodeName&&(a.preventDefault(),u.fire({newURL:a.target.hash.slice(1)}))};o=new f.Event(window,"scroll");(function(){l.detach();p.each(e.querySelectorAll("[data-jb-smoothscroll]"),function(a){A.push(new f.Event.Subscription("click",a,w))})})()});
paste.define("jawbone.ui.socialshare",["paste.dom","paste.util","paste.event","jawbone.google"],function(h,g,i,k,b){var j=g.querySelector(".jawbone-social-share"),f=window.Globals,a={facebookAppId:"",smallPicture:"",bigPicture:"",title:document.title,caption:"",description:"",shareUrl:"https://jawbone.com"+window.location.pathname+window.location.hash,redirectUrl:f?f.protocol+"//"+f.domain+"/www/close":"https://jawbone.com/www/close"},e=function(a,d,c,b){var e=(g.getViewportWidth()-c)/2,f=(g.getViewportHeight()-
b)/2;window.open(a,d,"top="+f+",left="+e+",width="+c+",height="+b)};new k.Event.Subscription("dosocialshare",j,function(l,d){if(d=d||!1)switch(d){case "facebook":var c="https://www.facebook.com/dialog/feed?app_id="+a.facebookAppId+"&link="+encodeURIComponent(a.shareUrl)+"&picture="+encodeURIComponent(a.bigPicture)+"&name="+encodeURIComponent(a.title)+"&caption="+encodeURIComponent(a.caption)+"&description="+encodeURIComponent(a.description)+"&redirect_uri="+encodeURIComponent(a.redirectUrl)+"&display=popup";
e(c,"",600,500);b.eventTracking.trackSocial({network:"Facebook",action:"ShareInit"});break;case "twitter":c="http://twitter.com/share?url="+encodeURIComponent(a.shareUrl)+"&text="+encodeURIComponent(a.title);e(c,"",600,500);b.eventTracking.trackSocial({network:"Twitter",action:"ShareInit"});break;case "google":c="https://plus.google.com/share?url="+encodeURIComponent(a.shareUrl);e(c,"",600,400);b.eventTracking.trackSocial({network:"Google",action:"ShareInit"});break;case "pinterest":c="http://pinterest.com/pin/create/button/?url="+
encodeURIComponent(a.shareUrl)+"&media="+encodeURIComponent(a.bigPicture)+"&description="+encodeURIComponent(a.title);e(c,"",700,300);b.eventTracking.trackSocial({network:"Pinterest",action:"ShareInit"});break;case "tumblr":c="http://www.tumblr.com/share/photo?source="+encodeURIComponent(a.bigPicture)+"&caption="+encodeURIComponent(a.title)+"&click_thru="+encodeURIComponent(a.shareUrl),e(c,"",600,500),b.eventTracking.trackSocial({network:"Tumblr",action:"ShareInit"})}});(function(){var b=i.dataset.get(j);
a=i.mixin(a,b,!0)})();h.setProperties=function(b){var d;if("object"===typeof b)for(d in b)a.hasOwnProperty(d)?a[d]=b[d]:window.console&&window.console.warn("Warning: Property '"+d+"' will not be used.");else throw Error("Properties must be passed as an object literal.");};h.getProperty=function(b){return a[b]}});
paste.define("jawbone.ui.stickynav",["paste.dom","paste.event"],function(m,b,c){var a=b.querySelector(".sticky-nav-target"),n=b.get("promo-holidays"),o,d,i,p,e,j,q,f,r,k,l,s,g,h,t,u,m="ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch;a&&!m&&(d=b.getDocumentBody(),o=document.getElementById("content"),i=document.getElementById("jawbone-nav"),q=parseInt(a.getAttribute("data-sticky-min-width"),10)||0,f=b.getScrollTop(),t=function(){!0!==a.stuck&&(p=b.Bounds.fromElement(i),
e=p.height,n&&(e+=b.Bounds.fromElement(n).height||22),j=b.Bounds.fromElement(a).top-e)},u=function(){r=b.getViewportWidth()},k=function(){r<=q||(f=b.getScrollTop(),f>=j?(a.stuck||d.classList.add("fixed-subnav"),a.stuck=!0,g=new c.Event(window,"navStuck"),g.fire(a),g.dispose(),g=null):f<j&&(!0===a.stuck&&d.classList.remove("fixed-subnav"),a.stuck=!1,h=new c.Event(window,"navUnstuck"),h.fire(a),h.dispose(),h=null))},l=function(){u();t();k()},s=function(){var a=b.querySelector(".fixed-nav-content",o);
a&&(a=a.cloneNode(!0),i.appendChild(a))},function(){d.classList.remove("fixed-subnav");s();c.DocumentEvent.loaded(function(){new c.Event.Subscription("scroll",window,k);new c.Event.Subscription("resize",window,l);l()})}())});
paste.define("jawbone.ui.socialHandler",["paste.dom","paste.event","jawbone.ui.socialshare"],function(a,e,c,f){var a=e.querySelector(".jawbone-social-share"),g=new c.Event(a,"dosocialshare");new c.Event.Subscription("click",a,function(d){var b=d.target,d=b.getAttribute("data-share-service"),a,c;d&&(a=b.getAttribute("data-share-image"),c=b.getAttribute("data-share-title"),b="facebook"===d?b.getAttribute("data-share-caption"):"",f.setProperties({bigPicture:a,title:c,caption:b}),g.fire(d))})});
